// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2d8b56b5ea0dd4, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2d8b56b5ea0dd4, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HelloResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2d8b56b5ea0dd4, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "proto.HelloResponse")
	proto.RegisterType((*User)(nil), "proto.User")
}

func init() { proto.RegisterFile("proto/greeter.proto", fileDescriptor_8a2d8b56b5ea0dd4) }

var fileDescriptor_8a2d8b56b5ea0dd4 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x3f, 0x0f, 0x82, 0x30,
	0x14, 0xc4, 0xa5, 0x80, 0x7f, 0x1e, 0xea, 0xf0, 0x70, 0x20, 0x4c, 0xd8, 0x89, 0x38, 0x60, 0x82,
	0xee, 0x8e, 0x3a, 0x39, 0x34, 0xf1, 0x03, 0x68, 0x78, 0x21, 0x24, 0x48, 0xb1, 0x85, 0xef, 0x6f,
	0x6c, 0x09, 0xea, 0xd4, 0xde, 0xbd, 0xcb, 0xdd, 0x0f, 0xc2, 0x56, 0xc9, 0x4e, 0xee, 0x4b, 0x45,
	0xd4, 0x91, 0xca, 0x8c, 0x42, 0xdf, 0x3c, 0x9c, 0xc3, 0xf2, 0x42, 0x75, 0x2d, 0x05, 0xbd, 0x7a,
	0xd2, 0x1d, 0x22, 0x78, 0xcd, 0xfd, 0x49, 0x91, 0x93, 0x38, 0xe9, 0x42, 0x98, 0x3f, 0xbf, 0xc2,
	0x6a, 0xc8, 0xe8, 0x56, 0x36, 0x9a, 0x30, 0x86, 0xb9, 0x29, 0xab, 0x9a, 0x72, 0x08, 0x8e, 0x1a,
	0xb7, 0xe0, 0xf7, 0x9a, 0x94, 0x8e, 0x58, 0xe2, 0xa6, 0x41, 0x1e, 0xd8, 0xb9, 0xec, 0xa6, 0x49,
	0x09, 0x7b, 0xe1, 0x3b, 0xf0, 0x3e, 0x12, 0xd7, 0xc0, 0xaa, 0xc2, 0x14, 0xb8, 0x82, 0x55, 0xc5,
	0xb8, 0xcd, 0xbe, 0xdb, 0xf9, 0x09, 0x66, 0x67, 0xcb, 0x8d, 0x47, 0xf0, 0x0d, 0x06, 0x86, 0x43,
	0xe7, 0x2f, 0x78, 0xbc, 0xf9, 0x37, 0x2d, 0x29, 0x9f, 0x3c, 0xa6, 0xc6, 0x3e, 0xbc, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0xd2, 0x1d, 0x82, 0x05, 0x01, 0x00, 0x00,
}
