// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbe

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DoubleSpending struct {
	_tab flatbuffers.Table
}

func GetRootAsDoubleSpending(buf []byte, offset flatbuffers.UOffsetT) *DoubleSpending {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DoubleSpending{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDoubleSpending(buf []byte, offset flatbuffers.UOffsetT) *DoubleSpending {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DoubleSpending{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DoubleSpending) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DoubleSpending) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DoubleSpending) Txs(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *DoubleSpending) TxsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DoubleSpendingStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DoubleSpendingAddTxs(builder *flatbuffers.Builder, txs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(txs), 0)
}
func DoubleSpendingStartTxsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DoubleSpendingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
