// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbe

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TxSpentBy struct {
	_tab flatbuffers.Table
}

func GetRootAsTxSpentBy(buf []byte, offset flatbuffers.UOffsetT) *TxSpentBy {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TxSpentBy{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTxSpentBy(buf []byte, offset flatbuffers.UOffsetT) *TxSpentBy {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TxSpentBy{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TxSpentBy) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TxSpentBy) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TxSpentBy) Position() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TxSpentBy) MutatePosition(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TxSpentBy) TxHash() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TxSpentByStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TxSpentByAddPosition(builder *flatbuffers.Builder, position int32) {
	builder.PrependInt32Slot(0, position, 0)
}
func TxSpentByAddTxHash(builder *flatbuffers.Builder, txHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(txHash), 0)
}
func TxSpentByEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
